name: vms_app
description: A demonstration and plugin for using Javascript with Flutter.
version: 0.8.1

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.6.0

dependencies:
  baseflow_plugin_template: ^2.1.2

  flutter:
    sdk: flutter

  geolocator: ^11.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1+1

  # The following adds the URL Launcher plugin which is used by
  # the demo application to open the links in the web browser.
  url_launcher: ^6.2.6
  provider: ^6.1.2 # Provider 패키지 추가
  ffi: ^2.0.0
  http: ^1.0.0
  sync_http: ^0.3.0
  dio: ^5.1.0
  logger: ^2.2.0
  flutter_dotenv: ^5.0.2
  shared_preferences: ^2.2.0
  crypto: ^3.0.0
  device_info_plus: ^11.2.1
  uuid: ^4.5.1
  android_id: ^0.2.0
  flutter_svg: ^2.0.7
  intl: ^0.18.1
  dotted_border: ^2.1.0
  table_calendar: ^3.0.6
  marquee: ^2.2.3
  get: ^4.6.6
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.4
  firebase_messaging: ^15.2.3
  firebase_analytics: ^11.4.3
  flutter_local_notifications: ^18.0.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  #collection: 1.19.0
  permission_handler: ^11.4.0
#  location: ^4.3.0
#  permission_handler: ^10.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/kdn/usm/img/
    - assets/kdn/ros/img/
    - assets/kdn/home/img/
    - assets/kdn/wid/img/
    - .env

  fonts:
    - family: PretendardVariable
      fonts:
        - asset: assets/kdn/font/woff2/PretendardVariable.woff2
