// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkaKS8B-_tiJwDpO7Ihy9Khz4THcFV5mA',
    appId: '1:49645199090:web:a6547164f3b2631292fa6b',
    messagingSenderId: '49645199090',
    projectId: 'vms-app-8ff6d',
    authDomain: 'vms-app-8ff6d.firebaseapp.com',
    storageBucket: 'vms-app-8ff6d.firebasestorage.app',
    measurementId: 'G-J64YHRFP8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmnn9lptZ-rU-XgKsdyVv24aU9SzBY28c',
    appId: '1:49645199090:android:76e62dad7afe760b92fa6b',
    messagingSenderId: '49645199090',
    projectId: 'vms-app-8ff6d',
    storageBucket: 'vms-app-8ff6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-89G_X7B0Zs5O_P0-trQYglmtax89EkE',
    appId: '1:49645199090:ios:d19f2d4850e1de7092fa6b',
    messagingSenderId: '49645199090',
    projectId: 'vms-app-8ff6d',
    storageBucket: 'vms-app-8ff6d.firebasestorage.app',
    iosBundleId: 'com.baseflow.geolocatorExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-89G_X7B0Zs5O_P0-trQYglmtax89EkE',
    appId: '1:49645199090:ios:71e2aa5658ac918b92fa6b',
    messagingSenderId: '49645199090',
    projectId: 'vms-app-8ff6d',
    storageBucket: 'vms-app-8ff6d.firebasestorage.app',
    iosBundleId: 'com.baseflow.example',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkaKS8B-_tiJwDpO7Ihy9Khz4THcFV5mA',
    appId: '1:49645199090:web:d490924c828b01ed92fa6b',
    messagingSenderId: '49645199090',
    projectId: 'vms-app-8ff6d',
    authDomain: 'vms-app-8ff6d.firebaseapp.com',
    storageBucket: 'vms-app-8ff6d.firebasestorage.app',
    measurementId: 'G-Y68WW7CP0Q',
  );
}
